---
- name: apt-cacher-ng setup
  hosts: proxy

  tasks:

  - name: apt-cacher-ng container
    docker:
      name: apt-cacher-ng
      image: konstruktoid/apt-cacher-ng
      command: VerboseLog=1 Debug=7 ForeGround=1 PassThroughPattern=.*
      state: reloaded
      ports:
      - "0.0.0.0:3124:3124"
      cap_drop: all
      pull: always
...
